### ISSUE TITLE
Question about libarary utilities

### ISSUE THREAD

**Issue by omerko** [indexexchange/undertone-adapter#10]
Hi, I wanted to make sure I understand some of the utility functions that I use

Browser.js - getHostname - 
Does it provide the top level frame hostname? or the current document hostname?

Browser.js - getPageUrl -
Same question - does it provide the top level url?

Thanks

**Comment by ix-certification** [comment]
## getHostName
Provides top level frame hostname

## getPageUrl
Provides top level url if called from the top window or document.referrer is an empty string

**Comment by omerko** [comment]
thanks
