### ISSUE TITLE
Fill Documentation.md file

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/undertone-adapter#18]
# Undertone
## General Compatibility
|Feature|  |
|---|---|
| Consent |  |
| Native Ad Support |  |
| SafeFrame Support |  |
| PMP Support | |
 
## Browser Compatibility
| Browser |  |
|--- |---|
| Chrome |  |
| Edge |  |
| Firefox |  |
| Internet Explorer 9 |  |
| Internet Explorer 10 |  |
| Internet Explorer 11 |  |
| Safari |  |
| Mobile Chrome | |
| Mobile Safari | |
| UC Browser | |
| Samsung Internet | |
| Opera | |
 
## Adapter Information
| Info | |
|---|---|
| Partner Id | UndertoneHtb |
| Ad Server Responds in (Cents, Dollars, etc) | |
| Bid Type (Gross / Net) | |
| GAM Key (Open Market) | |
| GAM Key (Private Market) | |
| Ad Server URLs | |
| Slot Mapping Sytle (Size / Multiple Sizes / Slot) | |
| Request Architecture (MRA / SRA) | |
 
### Parameters
| Key | Required | Type | Description |
|---|---|---|---|
| | | | |
 
### Example
```javascript
 
```
 
### Bid Example
```javascript
 
```
### Pass Example
```javascript
 
```
 
### Configuration Keys
| Key | Required | Type | Description |
|---|---|---|---|
| | | | |
### Example
```javascript
 
```

**Comment by ix-certification** [comment]
@omerko Also we would appreciate it if we can also ensure to fill out the changes.md file. Feel free to reference the following link which highlights the information that needs to be filled out here.
https://knowledgebase.indexexchange.com/display/ADAPTER/Adapter+Code+Submission+Guidelines

**Comment by omerko** [comment]
Done all in the existing PR
https://github.com/indexexchange/undertone-adapter/pull/17
