### ISSUE TITLE
Template literal may break on older browsers

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/undertone-adapter#5]
https://github.com/indexexchange/undertone-adapter/blob/d4fbdb07b68de64b8e230d95501d28705c5b8315/undertone-htb.js#L163-L179

Maximize browser compatibility by avoiding ES6 syntax.  The `requestUrl` variable can be eliminated entirely.  Add `pid` and `domain` properties to `queryObj` instead.  The queryObj is used to add query parameters to your request.  For each `property` and `value` in the object, `property=value` will be added as a query paramter

**Comment by omerko** [comment]
Removed the template literal,
regarding the query obj, it contains a hierarchical json structure of all the bids (for MRA support) in the POST body, this is not related to the url query parameters.
