### ISSUE TITLE
queryObj properties should map to string values

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/undertone-adapter#6]
https://github.com/indexexchange/undertone-adapter/blob/d4fbdb07b68de64b8e230d95501d28705c5b8315/undertone-htb.js#L163-L179

`queryObj` is used to add query parameters to the bid request.  Passing an array of objects results in the query parameter  `x-ut-hb-params[]: [object Object]`.  As a result the information inside the objects is lost.  Convert the array of objects to a string to generate the expected query parameters.

**Comment by omerko** [comment]
Removed the template literal,
regarding the query obj, it contains a hierarchical json structure of all the bids (for MRA support) in the POST body, this is not related to the url query parameters.
