### ISSUE TITLE
Missing closing meta script tag

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/undertone-adapter#7]
https://github.com/indexexchange/undertone-adapter/blob/d4fbdb07b68de64b8e230d95501d28705c5b8315/undertone-htb.js#L318-L321

Line 318 contains an opening metascript tag.  The closing metascript tag was removed.  As a result, the metascript parser will be unable to process this file. This will prevent the adapter from being built into a wrapper for testing.  Add `//? }` at line 320 so the file can parsed.

**Comment by omerko** [comment]
updated
