### ISSUE TITLE
Change publisherId to string

### ISSUE THREAD

**Issue by ix-certification** [indexexchange/undertone-adapter#8]
https://github.com/indexexchange/undertone-adapter/blob/d4fbdb07b68de64b8e230d95501d28705c5b8315/undertone-htb-validator.js#L49-L52

Typically the integer type is used for quantities only.  Using integer type for publisherId could cause issues when the code is minified.  Make publisherId a string instead.

**Comment by omerko** [comment]
our publisher id is sent in the json body as integer, and it's important to us that it will not be alphanumeric

**Comment by ix-certification** [comment]
You can leverage additional validation to avoid potential minification errors and ensure that the string supplied uses only numbers.  Use an exec function or a pattern in the schema to ensure only numbers are contained in the publisher id.  You can read more about these properties in [the schema validator readme](https://github.com/Atinux/schema-inspector)

**Comment by omerko** [comment]
updated
